Auto multi validation
egulias/EmailValidator pull request #335
Opened 2022-09-09 20:47 UTC by mariuszmalek

I created this branch to have every validation in one place by class name.

Example use:

```
$array = EmailValidatorFactory::create("my@email.com");
```

2022-09-10 07:04 UTC, mariuszmalek commented
Thanks to this, I can now easily handle all the information and save it in the database.

2022-10-01 13:51 UTC, egulias requested changes
Hey. Thanks for your patience. Leaving you here some comments.

2022-10-01 13:51 UTC, egulias commented on src/EmailValidatorFactory.php
> +    public static function create(string $emailAddress): array
Which are the reasons behing making it static? It prevents being injected as dependency.

2022-10-01 13:51 UTC, egulias commented on src/EmailValidatorFactory.php
> +        foreach (self::$defaultValidators as $key => $val) {
You could just use ´MultipleValidationWithAnd´ at construction time. And remove line 15.

2022-10-01 13:51 UTC, egulias commented on src/EmailValidatorFactory.php
> +    protected static array $defaultValidators = [
Are you expecting or encouraging extension? This prevents it. There is also no entry point to add additional/other validators than this.

You can do it via constructor arguments with sensible defaults (is like your idea here, but with simple extension point)

2022-10-01 13:51 UTC, egulias commented on src/EmailValidatorFactory.php
> +    public static function create(string $emailAddress): array
Also, you are returning the lists of results, not a validator ready for use. I'd suggest to change the name to something like `validationsResults` or similar.

2022-10-01 13:51 UTC, egulias commented on src/EmailValidatorFactory.php
> +        return $result;
Is the validator's `Result` type not useful? Maybe adding which validation is giving which result would be useful?

2024-12-26 23:53 UTC, egulias commented
Closing. Branch 3.x is no longer maintained.

2024-12-26 23:53 UTC, closed without merging